// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZ4BD9VeOO74xDv9-Aop71dh2bQuDTY2Q',
    appId: '1:102823603522:web:443c82ada50bb37884acdb',
    messagingSenderId: '102823603522',
    projectId: 'mindcare-24c96',
    authDomain: 'mindcare-24c96.firebaseapp.com',
    storageBucket: 'mindcare-24c96.firebasestorage.app',
    measurementId: 'G-L1JXQFHRQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGGIiszYXW6hPuf4mRshr_qt40Zur_hec',
    appId: '1:102823603522:android:ddf341d774ca807b84acdb',
    messagingSenderId: '102823603522',
    projectId: 'mindcare-24c96',
    authDomain: 'mindcare-24c96.firebaseapp.com',
    storageBucket: 'mindcare-24c96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGGIiszYXW6hPuf4mRshr_qt40Zur_hec',
    appId: '1:102823603522:ios:ddf341d774ca807b84acdb',
    messagingSenderId: '102823603522',
    projectId: 'mindcare-24c96',
    authDomain: 'mindcare-24c96.firebaseapp.com',
    storageBucket: 'mindcare-24c96.firebasestorage.app',
    iosBundleId: 'com.niostudio.mindcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGGIiszYXW6hPuf4mRshr_qt40Zur_hec',
    appId: '1:102823603522:ios:ddf341d774ca807b84acdb',
    messagingSenderId: '102823603522',
    projectId: 'mindcare-24c96',
    authDomain: 'mindcare-24c96.firebaseapp.com',
    storageBucket: 'mindcare-24c96.firebasestorage.app',
    iosBundleId: 'com.niostudio.mindcare',
  );
}